### ISSUE TITLE
_couldNotImportPyScreeze() got an unexpected keyword argument 'region'

### ISSUE THREAD

**Issue by chunlaiqingke** [tianqiraf/DouZero_for_JJ#38]
Traceback (most recent call last):
  File "/Users/zhaojun/github/DouZero_For_HappyDouDiZhu/main.py", line 115, in init_cards
    self.user_hand_cards_real = self.find_my_cards(self.MyHandCardsPos)
  File "/Users/zhaojun/github/DouZero_For_HappyDouDiZhu/main.py", line 292, in find_my_cards
    img = pyautogui.screenshot(region=pos)
TypeError: _couldNotImportPyScreeze() got an unexpected keyword argument 'region'

执行开始按钮之后报这个错

macos

**Comment by chunlaiqingke** [comment]
python3.9

**Comment by CokeYours** [comment]
我也是！！！python 3.9

**Comment by huiyidian** [comment]
大家解决了不

**Comment by wodaimnd** [comment]
Traceback (most recent call last):
File "E:\git\DouZero_For_HappyDouDiZhu-2.0\main.py", line 115, in init_cards
self.user_hand_cards_real = self.find_my_cards(self.MyHandCardsPos)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\git\DouZero_For_HappyDouDiZhu-2.0\main.py", line 290, in find_my_cards
img = pyautogui.screenshot(region=pos)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _couldNotImportPyScreeze() got an unexpected keyword argument 'region'

**Comment by azJoe123** [comment]
一样救救

**Comment by forgrabbit** [comment]
pip install --upgrade pyautogui可以解决
